version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: wordpass
    ports:
      - "9906:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./php/:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "9191:80"
    environment:
      PMA_ARBITRARY: 1

  # nginx:
  #   image: nginx:stable-alpine
  #   container_name: nginx
  #   ports:
  #     - 80:80
  #   networks:
  #     - default
  #   volumes:
  #     - ./php:/php
  #     - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
  #   depends_on:
  #     - web
  #
  # ngrok:
  #   image: wernight/ngrok:latest
  #   ports:
  #     - 4040:4040
  #   environment:
  #     NGROK_PROTOCOL: http
  #     NGROK_PORT: nginx:80
  #     NGROK_AUTH: {#}
  #   depends_on:
  #     - nginx
  #   networks:
  #     - default
